import '@emotion/react'
import { sky, gray, skyDark, grayDark } from '@radix-ui/colors';


declare module '@emotion/react' {
    export interface Theme {
        colors: {
            // Accent
            accent1: string
            accent2: string
            accent3: string
            accent4: string
            accent5: string
            accent6: string
            accent7: string
            accent8: string
            accent9: string
            accent10: string
            accent11: string
            accent12: string
            accentBackground1: string
            accentBackgroundA1: string
            accentBackground2: string
            accentBackgroundA2: string
            accentInteractive3: string
            accentInteractiveA3: string
            accentInteractive4: string
            accentInteractiveA4: string
            accentInteractive5: string
            accentInteractiveA5: string
            accentBorders6: string
            accentBordersA6: string
            accentBorders7: string
            accentBordersA7: string
            accentBorders8: string
            accentBordersA8: string
            accentSolid9: string
            accentSolidA9: string
            accentSolid10: string
            accentSolidA10: string
            accentText11: string
            accentTextA11: string
            accentText12: string
            accentTextA12: string

            // Neutral
            neutral1: string
            neutral2: string
            neutral3: string
            neutral4: string
            neutral5: string
            neutral6: string
            neutral7: string
            neutral8: string
            neutral9: string
            neutral10: string
            neutral11: string
            neutral12: string
            neutralBackground1: string
            neutralBackgroundA1: string
            neutralBackground2: string
            neutralBackgroundA2: string
            neutralInteractive3: string
            neutralInteractiveA3: string
            neutralInteractive4: string
            neutralInteractiveA4: string
            neutralInteractive5: string
            neutralInteractiveA5: string
            neutralBorders6: string
            neutralBordersA6: string
            neutralBorders7: string
            neutralBordersA7: string
            neutralBorders8: string
            neutralBordersA8: string
            neutralSolid9: string
            neutralSolidA9: string
            neutralSolid10: string
            neutralSolidA10: string
            neutralText11: string
            neutralTextA11: string
            neutralText12: string
            neutralTextA12: string

            // Success
            success1: string
            success2: string
            success3: string
            success4: string
            success5: string
            success6: string
            success7: string
            success8: string
            success9: string
            success10: string
            success11: string
            success12: string
            successBackground1: string
            successBackgroundA1: string
            successBackground2: string
            successBackgroundA2: string
            successInteractive3: string
            successInteractiveA3: string
            successInteractive4: string
            successInteractiveA4: string
            successInteractive5: string
            successInteractiveA5: string
            successBorders6: string
            successBordersA6: string
            successBorders7: string
            successBordersA7: string
            successBorders8: string
            successBordersA8: string
            successSolid9: string
            successSolidA9: string
            successSolid10: string
            successSolidA10: string
            successText11: string
            successTextA11: string
            successText12: string
            successTextA12: string

            // Danger
            danger1: string
            danger2: string
            danger3: string
            danger4: string
            danger5: string
            danger6: string
            danger7: string
            danger8: string
            danger9: string
            danger10: string
            danger11: string
            danger12: string
            dangerBackground1: string
            dangerBackgroundA1: string
            dangerBackground2: string
            dangerBackgroundA2: string
            dangerInteractive3: string
            dangerInteractiveA3: string
            dangerInteractive4: string
            dangerInteractiveA4: string
            dangerInteractive5: string
            dangerInteractiveA5: string
            dangerBorders6: string
            dangerBordersA6: string
            dangerBorders7: string
            dangerBordersA7: string
            dangerBorders8: string
            dangerBordersA8: string
            dangerSolid9: string
            dangerSolidA9: string
            dangerSolid10: string
            dangerSolidA10: string
            dangerText11: string
            dangerTextA11: string
            dangerText12: string


            // Contrast
            accentContrast: string
            neutralContrast: string
        },
    }
}